### ISSUE TITLE
fatal error: linux/vas.h No such file or directory

### ISSUE THREAD

**Issue by wxggg** [l3nkz/libmvas#4]
when I compile the project, I got this `fatal error: linux/vas.h No such file or directory` error. I am wondering what else I need to solve this.

**Comment by l3nkz** [comment]
Hi, you need the Linux headers of a kernel with the Multiple Virtual Address Spaces patches applied. Please look at the mvas branch of my Linux repository. It contains the latest version of the patches.

**Comment by sharixos** [comment]
Hello Smejkal, thanks very much for your reply and your work. I have tried what you mentioned about the MVAS-linux kernel, here's what i have done since then, but still got errors.

1.	At first I compile the libmvas project directly, but it have  fatal error: linux/vas.h No such file or directory error, now I know I need to compile and install the mvas-linux kernel

2.	I have tried several kinds of mvas-linux kernel, but things didn’t get better
	https://github.com/ranjansv/MVAS-CP-Linux-kernel
	https://github.com/l3nkz/linux/tree/mvas
	https://github.com/l3nkz/linux/tree/mvas-cp
I tried command ‘ find / -name vas.h’ , but can not find it in the system include dir /usr/include or /usr/local/include

3.	Then I tried to copy the needed headers from the Linux project, for example ‘cp -r ./include /usr/local’,  but there’s more and more errors

4.	The steps I do to compile mvas-cp kernel
	Git clone your Linux repositiory
	Git checkout -b mvas-cp origin/mvas-cp
	Copy my Linux config file to the current path,  cp /boot/config-(uname -r)… .config
	Make oldconfig, and now there’re many choices to make, **all things about VAS I chose y**
	Make -j6
	Make modules_install
	Make install 

5.	I do all these things on my virtualbox virtual machine
Ubuntu 16.04
Kernel: Linux-4.10.0.28

I don’t know if there’s any wrong operation upwards, I am wondering if there’s something wrong when I compile the kernel so that the header vas.h is not installed to the system path.

Appreciate your response!!! Thanks very much !!!
